name: weathershare
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.16.0
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.19.0
  firebase_core: ^2.29.0
  firebase_ui_auth: ^1.13.1
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_otp_text_field: ^1.1.3+2
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.0
  liquid_swipe: ^3.1.0
  logger: ^2.2.0
  provider: ^6.1.2
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "#272727"
  image: assets/icons/splash.png
  image_dark: assets/icons/splash.png

  android_12:
    image: assets/icons/splash.png
    icon_background_color: "#ffffff"
    image_dark: assets/icons/splash.png
    icon_background_color_dark: "#121212"
  web: false

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/onboarding_images/
    - assets/images/welcome_images/
    - assets/images/login_images/
    - assets/images/signup_images/

    - assets/logo/
