// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUyoPTVDb_ylvEOVJ67PNjg3dS-PK5VqE',
    appId: '1:987829177165:web:9326114a5b04052146c504',
    messagingSenderId: '987829177165',
    projectId: 'weathershare-a93a0',
    authDomain: 'weathershare-a93a0.firebaseapp.com',
    storageBucket: 'weathershare-a93a0.appspot.com',
    measurementId: 'G-7J0RP9X4GM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc48Vx71j2WFwHk9AUMED4Kms_FByEB0A',
    appId: '1:987829177165:android:ffb0feb38e8e00ef46c504',
    messagingSenderId: '987829177165',
    projectId: 'weathershare-a93a0',
    storageBucket: 'weathershare-a93a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYTH5K8AJCTivhi1p7WUNkKGLGdPCpmeQ',
    appId: '1:987829177165:ios:4a79c0d8e652266f46c504',
    messagingSenderId: '987829177165',
    projectId: 'weathershare-a93a0',
    storageBucket: 'weathershare-a93a0.appspot.com',
    androidClientId: '987829177165-e4ge8q1mstn2nk5gsldcbk8rvt7srlom.apps.googleusercontent.com',
    iosClientId: '987829177165-gdtpc6t4svr4dcvdbdh3f4924uhncnl7.apps.googleusercontent.com',
    iosBundleId: 'com.example.weathershare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYTH5K8AJCTivhi1p7WUNkKGLGdPCpmeQ',
    appId: '1:987829177165:ios:4a79c0d8e652266f46c504',
    messagingSenderId: '987829177165',
    projectId: 'weathershare-a93a0',
    storageBucket: 'weathershare-a93a0.appspot.com',
    androidClientId: '987829177165-e4ge8q1mstn2nk5gsldcbk8rvt7srlom.apps.googleusercontent.com',
    iosClientId: '987829177165-gdtpc6t4svr4dcvdbdh3f4924uhncnl7.apps.googleusercontent.com',
    iosBundleId: 'com.example.weathershare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUyoPTVDb_ylvEOVJ67PNjg3dS-PK5VqE',
    appId: '1:987829177165:web:4a260af1eaa38d0546c504',
    messagingSenderId: '987829177165',
    projectId: 'weathershare-a93a0',
    authDomain: 'weathershare-a93a0.firebaseapp.com',
    storageBucket: 'weathershare-a93a0.appspot.com',
    measurementId: 'G-02P40YFJRQ',
  );

}