// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOGJLp0jShZH1G6cxcAjzFhD8JpfmV5LM',
    appId: '1:205985847642:web:8ecfbc07026ade43c73b63',
    messagingSenderId: '205985847642',
    projectId: 'weathershare-d2b77',
    authDomain: 'weathershare-d2b77.firebaseapp.com',
    storageBucket: 'weathershare-d2b77.appspot.com',
    measurementId: 'G-9W60JY02VL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgUYdI_7D-nPXxDynAQAvtHJ6Fyz36C3c',
    appId: '1:205985847642:android:fa436fe9e94b0e28c73b63',
    messagingSenderId: '205985847642',
    projectId: 'weathershare-d2b77',
    storageBucket: 'weathershare-d2b77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUmvNAm4O7JNKN8jsqAJ8yAP4GAZhd5Bc',
    appId: '1:205985847642:ios:4aaec989b11d9a70c73b63',
    messagingSenderId: '205985847642',
    projectId: 'weathershare-d2b77',
    storageBucket: 'weathershare-d2b77.appspot.com',
    iosBundleId: 'com.example.weathershare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUmvNAm4O7JNKN8jsqAJ8yAP4GAZhd5Bc',
    appId: '1:205985847642:ios:a1ca81b55b97b7ffc73b63',
    messagingSenderId: '205985847642',
    projectId: 'weathershare-d2b77',
    storageBucket: 'weathershare-d2b77.appspot.com',
    iosBundleId: 'com.example.weathershare.RunnerTests',
  );
}
